### ISSUE TITLE
Enhancement - Enabling parallel via OpenMP

### ISSUE THREAD

**Issue by marioroy** [josch/mandelbrot#2]
Greetings,

I updated `mandel_dd_aa.c` and enabled parallel using OpenMP. See [Gist](https://gist.github.com/marioroy/7c95d314cab080ad6d6b6d90a5fcbff9).

```text
$ time ./mandel_dd_aa 1920 1080 -0.75 0.0 1.0 > out.ppm
AA: 99.907410 %

real  0m17.836s
user  0m17.787s
sys   0m0.015s

$ time OMP_NUM_THREADS=4 ./mandel_dd_aa_omp 1920 1080 -0.75 0.0 1.0 > out.ppm
AA: 99.722221 %

real  0m4.568s
user  0m18.056s
sys   0m0.011s

$ time OMP_NUM_THREADS=8 ./mandel_dd_aa_omp 1920 1080 -0.75 0.0 1.0 > out.ppm
AA: 99.351852 %

real  0m2.331s
user  0m18.363s
sys   0m0.006s
```

Both entries use the same source file in the Makefile.

```text
mandel_dd_aa: mandel_dd_aa.c
    gcc -O3 -Wall -Wno-unknown-pragmas -lm mandel_dd_aa.c -o mandel_dd_aa

mandel_dd_aa_omp: mandel_dd_aa.c
    gcc -O3 -Wall -fopenmp -lm mandel_dd_aa.c -o mandel_dd_aa_omp
```

This was lots of fun and created a big Mandelbrot consuming all CPU cores.

Regards, Mario

**Comment by josch** [comment]
If you like, feel free to open a pull request and then I can integrate your improvements.

Same goes for the other issue you found a fix for. :)
